spring.application.name=jobpulse
spring.datasource.url=jdbc:postgresql://localhost:5432/jobpulse
spring.datasource.username=jobpulse
spring.datasource.password=jobpulse

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

